### ISSUE TITLE
first name/surname order?

### ISSUE THREAD

**Issue by Skyler84** [ecss-soton/verify#10]
https://github.com/ecss-soton/verify/blob/25001963bec592d1ec14721ee30dfe5da951d99d/pages/api/auth/%5B...nextauth%5D.ts#L121-L122

Looks like this might be wrong order or is there something strange behind the scenes. I don't think it affects much, just curious why it's like this

**Comment by miam-miam** [comment]
:joy: For some strange reason when @Ortovoxx first designed the thing the db data had first and last names the wrong way round. So instead of writing a migration we just swapped the two whenever we read from the db.

Some truly top notch programming
